dataset_path: TIGER-Lab/Mantis-Eval
task: "mantis_eval"
dataset_kwargs:
  token: True
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mantis_doc_to_visual
doc_to_text: !function utils.mantis_doc_to_text
doc_to_target: !function utils.mantis_doc_to_target
process_results: !function utils.mantis_process_results
  
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."


generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.MultiChoiceRegexFilter
        group_select: 0
        ignore_case: true
        ignore_punctuation: true
        regex_pattern: "([A-Z])\\."

metric_list:
  - metric: mantis_score_overall
    aggregation: !function utils.mantis_aggregation 
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true

metadata:
  - version: 0.0
