dataset_path: Efficient-Large-Model/BLINK
task: "blink"
dataset_kwargs:
  token: True
test_split: val
output_type: generate_until
doc_to_visual: !function utils.blink_doc_to_visual
doc_to_text: !function utils.blink_doc_to_text
doc_to_target: !function utils.blink_doc_to_target
process_results: !function utils.blink_process_results


generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  do_sample: False

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.MultiChoiceRegexFilter
        group_select: 0
        ignore_case: true
        ignore_punctuation: true
        regex_pattern: "([A-Z])\\."

metric_list:
  - metric: blink_score_overall
    aggregation: !function utils.blink_aggregation 
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true

metadata:
  - version: 0.0
